server:
  port: 10022
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tothecloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "123456"
  jackson:
    time-zone: GMT+8
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 200
      host: 148.70.99.98
      password: "on99"
  kafka:
    bootstrap-servers: 127.0.0.1:19911
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: NacosInit
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
  application:
    name: OfficesService
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        cluster-name: nanjing
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  profiles:
    active: nacos
logging:
  level:
    root: info


