spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class_design?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "123456"
  jackson:
    time-zone: GMT+8

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty
